server:
  port: 8511
  servlet:
    context-path: /
logging:
  config: classpath:logback-dev.xml
##自定义配置
jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1/local_demo?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
  user: root
  password: root
mybatisConfigLocation: mybatis-config-dev.xml