spring:
  profiles:
    active: dev
  application:
    name: boot-ssm
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
      max-connections: 10
#   自定义
    trustedPackages: com.tequeno.common.mq,java.util,java.lang
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: mysql
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# 自定义配置
mapperLocation: /mapper/**/*.xml
entityLocation: com.tequeno.bootssm.pojo
# 自定义
rocketmq:
  groupName: r_group
  topic: r_topic
# *表示订阅当前topic下所有的tag,配置特殊字符需要使用'(英文半角单引号)
  subExpression: '*'
  namesrvAddr: 127.0.0.1:9876
  failedRetry: 0
  vipEnabled: false