server:
  port: 8510
  servlet:
    context-path: /
spring:
  application:
    name: boot-assembly
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
#    password: 87aba0cb443ddce282f333a63b463ee2
    timeout: 10000
    #    连接耗尽时是否阻塞, false报异常,true阻塞直到超时, 默认true
    block-when-exhausted: false
    #    是否启用pool的jmx管理功能, 默认true
    jmx-enabled: false
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 10000
logging:
  config: ${spring.config.location}/logback.xml
# activemq
activemq:
  user: admin
  password: admin
  broker-url: tcp://127.0.0.1:61616
  trustedPackages: com.tequeno.common.mq,java.util,java.lang
# rocketmq
rocketmq:
  producerGroup: r_group
  namesrvAddr: 127.0.0.1:9876
  producer:
    retryTimesWhenSendFailed: 2
    retryTimesWhenSendAsyncFailed: 2
    vipChannelEnabled: false
    instanceName: producerInstance
    sendMsgTimeout: 3000
    maxMessageSize: 4194304
  consumer:
    topic: r_topic
    #   *表示订阅当前topic下所有的tag,配置特殊字符需要使用'(英文半角单引号)
    #   || 表示同时订阅当前topic下多个tag 比如 r_tag_a || r_tag_b
    subExpression: '*'
    instanceName: consumerInstance
    #    消费者一次接收消息最大数量
    consumeMessageBatchMaxSize: 1
    #    以上配置都是默认配置
    consumeTimeout: 3000 #默认15
    consumeThreadMin: 10 #默认20
    consumeThreadMax: 30 #默认20
file:
  upload: /hexk/github/hey-jude/deploy/data/upload/
  template: /hexk/github/hey-jude/deploy/data/template/
  lua: doc/lua/
#启动参数
#-Dspring.config.location=doc/assembly/