server:
  port: 8500
  servlet:
    context-path: /
spring:
  redis:
    database: 1
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
      max-connections: 10
#   自定义
    trustedPackages: com.tequeno.common.mq,java.util,java.lang
logging:
  config: classpath:logback-spring.xml
# 自定义
rocketmq:
  groupName: r_group_test_a
  topic: r_topic_test_a
# *表示订阅当前topic下所有的tag,配置特殊字符需要使用'(英文半角单引号)
  subExpression: '*'
# || 表示同时订阅当前topic下多个tag
# subExpression: r_tag_a || r_tag_b
  namesrvAddr: 127.0.0.1:9876
  failedRetry: 0
  vipEnabled: false