server:
  port: 8500
  servlet:
    context-path: /
spring:
  redis:
    database: 1
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
      max-connections: 10
logging:
  config: classpath:logback-spring.xml