server:
  port: 8521
  servlet:
    context-path: /
spring:
  application:
    name: dubbo-consumer
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: redis://127.0.0.1
    port: 6379
    #指定注册到注册中心上超时时间，ms
    timeout: 10000
  #指定dubbo使用的协议、端口
  protocol:
    name: dubbo
    port: 20880
  #启动应用时是否检查注册中心上有没有依赖的服务，默认true
  consumer:
    check: false