spring:
  application:
    name: dubbo-consumer
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://192.168.1.9
    port: 2181
    #指定注册到zk上超时时间，ms
    timeout: 10000
  #指定dubbo使用的协议、端口
  protocol:
    name: dubbo
    port: 20880
  #启动应用时是否检查注册中心上有没有依赖的服务，默认true
  consumer:
    check: false