spring:
  application:
    name: eureka-server
server:
  port: 1001
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka